# Generated by Django 3.2 on 2023-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='field',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
