# Generated by Django 3.2 on 2023-01-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='field',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
