# Generated by Django 3.2 on 2023-01-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.IntegerField(default=1),
        ),
    ]
